---
title: "Setting a Password"
---

> Every surveydown survey needs a password to secure access to the survey data. You should set one password for each project.

# Setting your project password

To set your surveydown password in a given project, run:

```{r}
sd_set_password("your_password")
```

> Warning: Do **NOT** put the `sd_set_password()` function in your `.qmd` file!

This is designed to be run once in your R console and not again (unless you want to change the password).

# What does this do?

By running `sd_set_password()`, a `.Renviron` file is created in your project directory that contains your password. This file is used to access your database and write data to it, as well as provide access to the admin page. **This file must remain in the root project directory - do not modify it**.

The call to `sd_set_password()` also adds a `.gitignore` file in your project with `.Renviron` in it, so it won't be accidentally pushed to GitHub. If a `.gitignore` file already exists, it will be updated to include `.Renviron`.

# What is the password used for?

Your password is used for two purposes:

1. Obtaining access to the [admin page](config.qmd#admin-page) of your survey.
2. Obtaining access to the Supabase database storing your survey data (see [Database Settings](database.qmd)).
