---
title: "Templates"
toc: false
---

To help you get started with surveydown, we created some templates that cover many of the features of the package. Feel free to use any as a starting point for your own surveys or as a reference for specific features. 

::: {.text-center}

[<button type="button" class="btn btn-primary btn-lg">{{< fa brands github >}} View the templates repo</button>](https://github.com/surveydown-dev/templates)

:::

Brief description of each template:

|  | Folder | Description |
|-------|--------|-------------|
| <i class="fa fa-list-ul" aria-hidden="true"></i> | question-types<br>[Access Template](https://surveydown.shinyapps.io/types/) | A template of all the [question types](docs/question-types.html) currently supported by surveydown. |
| <i class="fa fa-eye" aria-hidden="true"></i> | conditional-display<br>[Access Template](https://surveydown.shinyapps.io/showif/) | A template of [conditional display](docs/conditional-question-display.qmd) (showing a question based on a previous response). |
| <i class="fa fa-forward" aria-hidden="true"></i> | conditional-skipping<br>[Access Template](https://surveydown.shinyapps.io/skipif/) | A template of [conditional survey flow (page skipping)](docs/conditional-survey-flow.qmd) (skipping to a page based on a previous response). |
| <i class="fa fa-balance-scale" aria-hidden="true"></i> | conjoint-buttons<br>[Access Template](https://surveydown.shinyapps.io/conjoint/) | A template of a choice-based conjoint survey using a button layout for the choice questions. |
| <i class="fa fa-balance-scale" aria-hidden="true"></i> | conjoint-tables<br>[Access Template](https://surveydown2.shinyapps.io/conjoint2/) | A template of a choice-based conjoint survey using a table layout for the choice questions. |
| <i class="fa fa-random" aria-hidden="true"></i> | random-labels<br>[Access Template](https://surveydown.shinyapps.io/random/) | A template of [random labels](docs/reactivity.html#randomizing-question-labels). |
| <i class="fa fa-shuffle" aria-hidden="true"></i> | random-labels-preset<br>[Access Template](https://surveydown2.shinyapps.io/random2/) | A template of [predefined random labels](docs/randomization.html). |
| <i class="fa fa-code-compare" aria-hidden="true"></i> | reactive-question<br>[Access Template](https://surveydown2.shinyapps.io/reactive/) | A template of [a reactive question](docs/reactivity.html#defining-questions-in-the-server-function). |
| <i class="fa fa-car" aria-hidden="true"></i> | reactive-drilldown<br>[Access Template](https://surveydown3.shinyapps.io/drilldown/) | A [reactive question](docs/reactivity.html#defining-questions-in-the-server-function) template of `drilldown`, in which latter question options are defined from the former selection. |
| <i class="fa fa-map-location-dot" aria-hidden="true"></i> | custom-leaflet-map<br>[Access Template](https://surveydown2.shinyapps.io/leaflet/) | A template of a custom leaflet map in your survey using the [`sd_question_custom()`](docs/custom-questions.html) function. |
| <i class="fa fa-chart-line" aria-hidden="true"></i> | custom-plotly-chart<br>[Access Template](https://surveydown2.shinyapps.io/plotly/) | A template of a custom plotly chart in your survey using the [`sd_question_custom()`](docs/custom-questions.html) function. |
| <i class="fa fa-up-right-from-square" aria-hidden="true"></i> | external-redirect | A template of external redirection links in your survey. |
| <i class="fa fa-chart-bar" aria-hidden="true"></i> | live-pulling | A template of live-pulling with a reactive plot (a summary plot of all prior response data updated in real time). |
