---
title: "Features & Roadmap"
execute: 
  echo: false
  message: false
  warning: false
toc: true
format:
  html:
    link-external-newwindow: false
    grid:
      body-width: 700px
eval: true
---

```{r setup}
library(tinytable)

# Get df from todo repo
df <- read.csv(
  "https://raw.githubusercontent.com/surveydown-dev/todo/refs/heads/main/df.csv",
  check.names = FALSE
)

# Separate incompletes
# Separate dataframes by Progress value
feature_ids <- which(df$Progress == 1)
todo_ids <- which(df$Progress == 2)
feature_apps_ids <- which(df$Progress == 3)
todo_apps_ids <- which(df$Progress == 4)

# Remove Progress column
df$Progress <- NULL

# Create separate dataframes
feature_df <- df[feature_ids,]
todo_df <- df[todo_ids,]
feature_apps_df <- df[feature_apps_ids,]
todo_apps_df <- df[todo_apps_ids,]

# Order feature dataframes by Version
feature_df <- feature_df[order(feature_df$Version),]
feature_apps_df <- feature_apps_df[order(feature_apps_df$Version),]
```

### Features - surveydown

```{r}
#| eval: true
feature_df |> 
  tt(theme = "grid", width = c(0.5, 0.2, 0.1, 0.1)) |>
  style_tt(fontsize = 1) |> 
  style_tt(j = c(1, 2), align = "l") |> 
  style_tt(j = c(3, 4), align = "c") |> 
  style_tt(i = 0, align = "c") |> 
  format_tt(quarto = TRUE)
```

### To Do - surveydown

```{r}
#| eval: true

todo_df |>
  tt(theme = "grid", width = c(0.5, 0.2, 0.1, 0.1)) |>
  style_tt(fontsize = 1) |> 
  style_tt(j = c(1, 2), align = "l") |> 
  style_tt(j = c(3, 4), align = "c") |> 
  style_tt(i = 0, align = "c") |> 
  format_tt(quarto = TRUE)
```

### Features - sdApps

```{r}
feature_apps_df |> 
  tt(theme = "grid", width = c(0.5, 0.2, 0.1, 0.1)) |>
  style_tt(fontsize = 1) |> 
  style_tt(j = c(1, 2), align = "l") |> 
  style_tt(j = c(3, 4), align = "c") |> 
  style_tt(i = 0, align = "c") |> 
  format_tt(quarto = TRUE)
```

### To Do - sdApps

```{r}
todo_apps_df |>
  tt(theme = "grid", width = c(0.5, 0.2, 0.1, 0.1)) |>
  style_tt(fontsize = 1) |> 
  style_tt(j = c(1, 2), align = "l") |> 
  style_tt(j = c(3, 4), align = "c") |> 
  style_tt(i = 0, align = "c") |> 
  format_tt(quarto = TRUE)
```
