name: Build and Deploy Quarto Site

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
  schedule:
    # Scheduled to run at midnight EST (5:00 UTC) every Sunday
    - cron: '0 5 * * 0'

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Setup pandoc"
        uses: r-lib/actions/setup-pandoc@v2

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2

      - name: "Setup R dependencies for Quarto's knitr engine"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            cran::dplyr
            cran::htmltools
            cran::knitr
            cran::leaflet
            cran::markdown
            cran::plotly
            cran::rmarkdown
            cran::sf
            cran::surveydown
            cran::tinytable

      - name: Install other R packages with dependencies
        run: |
          install.packages(c('sf', 'leaflet', 'plotly'), dependencies=TRUE, repos='https://cloud.r-project.org/')
          install.packages("pkgdown")
        shell: Rscript {0}

      # - name: Check Urls
      #   uses: lycheeverse/lychee-action@v1.9.0
      #   with:
      #     args: --verbose --no-progress './_site/**/*.html'
      #     fail: true  # Optional: set to false if you don't want the workflow to fail on broken links
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}